import {

    useState

} from "react";

import toast from "react-hot-toast";

import jsPDF from "jspdf";

import {

    getAnalytics,
    notifyCSVExport

} from "../../services/analyticsService";

function ExportCenter() {

    const [loading, setLoading] = useState(false);

    // CSV EXPORT

    const exportCSV = async () => {

        try {

            setLoading(true);

            const analytics = await getAnalytics();

            const csvData = [

                ["Metric", "Value"],

                ["Total Usage", analytics.totalUsage],

                ["Average Usage", analytics.averageUsage],

                ["Indoor Usage", analytics.indoorUsage],

                ["Outdoor Usage", analytics.outdoorUsage],

                ["Eco Score", analytics.ecoScore],

                ["Prediction", analytics.prediction]
            ];

            const csvContent = csvData

                .map((row) => row.join(","))

                .join("\n");

            const blob = new Blob(

                [csvContent],

                {

                    type: "text/csv;charset=utf-8;"
                }
            );

            const url = URL.createObjectURL(blob);

            const link = document.createElement("a");

            link.href = url;

            link.setAttribute(

                "download",

                "hydropulse-report.csv"
            );

            document.body.appendChild(link);

            link.click();

            document.body.removeChild(link);

            toast.success(

                "CSV Report Exported Successfully"
            );

            // Notify backend to dispatch confirmation email
            notifyCSVExport().catch((emailErr) => {
                console.error("Failed to trigger CSV export notification email:", emailErr);
            });

        } catch (error) {

            console.log(error);

            toast.error(

                "CSV Export Failed"
            );

        } finally {

            setLoading(false);
        }
    };

    // REAL PDF EXPORT

    const exportPDF = async () => {

        try {

            setLoading(true);

            const analytics = await getAnalytics();

            const doc = new jsPDF();

            // HEADER

            doc.setFontSize(24);

            doc.text(

                "HydroPulse Sustainability Report",

                20,

                25
            );

            doc.setFontSize(12);

            doc.text(

                `Generated: ${new Date().toLocaleString()}`,

                20,

                35
            );

            // LINE

            doc.line(20, 42, 190, 42);

            // ANALYTICS

            doc.setFontSize(18);

            doc.text(

                "Analytics Summary",

                20,

                55
            );

            doc.setFontSize(13);

            doc.text(

                `Total Usage: ${analytics.totalUsage}L`,

                20,

                70
            );

            doc.text(

                `Average Usage: ${analytics.averageUsage}L`,

                20,

                80
            );

            doc.text(

                `Indoor Usage: ${analytics.indoorUsage}L`,

                20,

                90
            );

            doc.text(

                `Outdoor Usage: ${analytics.outdoorUsage}L`,

                20,

                100
            );

            doc.text(

                `Eco Score: ${analytics.ecoScore}%`,

                20,

                110
            );

            doc.text(

                `Prediction: ${analytics.prediction}L`,

                20,

                120
            );

            // AI SUMMARY

            doc.setFontSize(18);

            doc.text(

                "AI Sustainability Insights",

                20,

                145
            );

            doc.setFontSize(12);

            let aiText =
                "HydroPulse AI detected balanced sustainability performance with efficient water utilization patterns.";

            if (analytics.averageUsage > 200) {

                aiText =
                    "High consumption detected. Reducing outdoor usage and shower duration may improve sustainability.";
            }

            if (analytics.averageUsage < 120) {

                aiText =
                    "Excellent sustainability performance detected with optimized water efficiency.";
            }

            doc.text(

                aiText,

                20,

                160,

                {

                    maxWidth: 170
                }
            );

            // FOOTER

            doc.setFontSize(10);

            doc.text(

                "Generated by HydroPulse Analytics Platform",

                20,

                285
            );

            // SAVE PDF

            doc.save(

                "hydropulse-report.pdf"
            );

            toast.success(

                "PDF Report Exported Successfully"
            );

        } catch (error) {

            console.log(error);

            toast.error(

                "PDF Export Failed"
            );

        } finally {

            setLoading(false);
        }
    };

    return (

        <div className="mt-10 max-w-2xl mx-auto">

            {/* EXPORT CENTER */}

            <div className="backdrop-blur-xl bg-white/5 border border-white/10 rounded-[32px] p-10 shadow-2xl">

                <div className="flex items-center gap-5">

                    <div className="w-20 h-20 rounded-3xl bg-cyan-500/20 flex items-center justify-center text-4xl">

                        📄

                    </div>

                    <div>

                        <h2 className="text-4xl font-black text-white">

                            Export Reports

                        </h2>

                        <p className="mt-2 text-gray-400">

                            Download sustainability analytics and reports

                        </p>

                    </div>

                </div>

                {/* BUTTONS */}

                <div className="mt-10 grid md:grid-cols-2 gap-5">

                    <button

                        onClick={exportCSV}

                        disabled={loading}

                        className="w-full py-5 rounded-2xl bg-cyan-500 hover:bg-cyan-400 transition text-black font-bold text-lg cursor-pointer"

                    >

                        Export CSV Report

                    </button>

                    <button

                        onClick={exportPDF}

                        disabled={loading}

                        className="w-full py-5 rounded-2xl bg-white/5 border border-white/10 hover:border-cyan-400 transition text-white font-bold text-lg cursor-pointer"

                    >

                        Export PDF Summary

                    </button>

                </div>

            </div>

        </div>
    );
}

export default ExportCenter;