import {

    useEffect,
    useState

} from "react";

import toast from "react-hot-toast";

function ReportsHistory() {

    const [reports, setReports] = useState([]);

    // LOAD REPORT HISTORY

    useEffect(() => {

        const storedReports = localStorage.getItem(

            "hydropulse_reports_history"
        );

        if (storedReports) {

            setReports(

                JSON.parse(storedReports)
            );

        } else {

            // DEFAULT REPORTS

            const defaultReports = [

                {
                    id: 1,

                    name: "Monthly Analytics Report",

                    type: "CSV",

                    date: new Date().toLocaleDateString(),

                    status: "Completed"
                },

                {
                    id: 2,

                    name: "Water Usage Summary",

                    type: "PDF",

                    date: new Date().toLocaleDateString(),

                    status: "Generated"
                }
            ];

            setReports(defaultReports);

            localStorage.setItem(

                "hydropulse_reports_history",

                JSON.stringify(defaultReports)
            );
        }

    }, []);

    // GENERATE REPORT

    const generateReport = () => {

        const newReport = {

            id: Date.now(),

            name: `Sustainability Report #${reports.length + 1}`,

            type: "CSV",

            date: new Date().toLocaleDateString(),

            status: "Completed"
        };

        const updatedReports = [

            newReport,

            ...reports
        ];

        setReports(updatedReports);

        localStorage.setItem(

            "hydropulse_reports_history",

            JSON.stringify(updatedReports)
        );

        toast.success(

            "New report generated successfully"
        );
    };

    // DOWNLOAD REPORT

    const downloadReport = (report) => {

        const reportContent = `

HydroPulse Sustainability Report

---------------------------------

Report Name: ${report.name}

Report Type: ${report.type}

Generated Date: ${report.date}

Status: ${report.status}

---------------------------------

Generated by HydroPulse Analytics Platform
        `;

        const blob = new Blob(

            [reportContent],

            {

                type: "text/plain"
            }
        );

        const url = URL.createObjectURL(blob);

        const link = document.createElement("a");

        link.href = url;

        link.setAttribute(

            "download",

            `${report.name}.txt`
        );

        document.body.appendChild(link);

        link.click();

        document.body.removeChild(link);

        toast.success(

            "Report downloaded successfully"
        );
    };

    return (

        <div className="mt-10 backdrop-blur-xl bg-white/5 border border-white/10 rounded-[32px] p-10 overflow-x-auto">

            {/* HEADER */}

            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-6 mb-10">

                <div>

                    <h2 className="text-4xl font-black text-white">

                        Report History

                    </h2>

                    <p className="mt-2 text-gray-400">

                        Generated analytics exports and synchronization history

                    </p>

                </div>

                <button

                    onClick={generateReport}

                    className="px-6 py-4 rounded-2xl bg-cyan-500 hover:bg-cyan-400 transition text-black font-bold"

                >

                    Generate Report

                </button>

            </div>

            {/* TABLE */}

            <table className="w-full">

                <thead>

                    <tr className="text-left text-gray-400 border-b border-white/10">

                        <th className="pb-5">

                            Report Name
                        </th>

                        <th className="pb-5">

                            Type
                        </th>

                        <th className="pb-5">

                            Date
                        </th>

                        <th className="pb-5">

                            Status
                        </th>

                        <th className="pb-5">

                            Actions
                        </th>

                    </tr>

                </thead>

                <tbody>

                    {
                        reports.map((item) => (

                            <tr
                                key={item.id}
                                className="border-b border-white/5"
                            >

                                {/* NAME */}

                                <td className="py-6 text-white font-semibold">

                                    {item.name}

                                </td>

                                {/* TYPE */}

                                <td className="py-6 text-cyan-300">

                                    {item.type}

                                </td>

                                {/* DATE */}

                                <td className="py-6 text-gray-400">

                                    {item.date}

                                </td>

                                {/* STATUS */}

                                <td className="py-6">

                                    <span className="px-4 py-2 rounded-xl bg-emerald-500/20 text-emerald-300">

                                        {item.status}

                                    </span>

                                </td>

                                {/* ACTIONS */}

                                <td className="py-6">

                                    <button

                                        onClick={() => {

                                            downloadReport(item);
                                        }}

                                        className="px-5 py-2 rounded-xl bg-cyan-500/20 text-cyan-300 hover:bg-cyan-500/30 transition"

                                    >

                                        Download

                                    </button>

                                </td>

                            </tr>
                        ))
                    }

                </tbody>

            </table>

            {/* EMPTY STATE */}

            {
                reports.length === 0 && (

                    <div className="py-20 text-center">

                        <h3 className="text-3xl font-black text-white">

                            No Reports Generated
                        </h3>

                        <p className="mt-3 text-gray-400">

                            Generate sustainability reports to view history

                        </p>

                    </div>
                )
            }

        </div>
    );
}

export default ReportsHistory;